name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "2165d01d-c56a-445f-9e47-6e9e9fc0cfd3"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "a5807ee06a9146e7ab3289d9e0aa2470"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
